JFG-1033: update jenkins plugins versions and fix some issues
griddynamics/jagger-jaas-jenkins-plugin pull request #2
Opened 2016-12-14 14:10 UTC by anton-antonenko

2016-12-15 11:52 UTC, SokolAndrey approved these changes

2016-12-16 09:30 UTC, dlatnikov requested changes

2016-12-16 09:30 UTC, dlatnikov commented on src/main/webapp/help-testProjectUrl.html
> +    Specify path (URL) to the jar with your test project. (URL must begin with 'file://')
it is incorrect. what about URL to nexus artefacts. they will begin with http

2016-12-16 09:43 UTC, anton-antonenko commented on src/main/webapp/help-testProjectUrl.html
> +    Specify path (URL) to the jar with your test project. (URL must begin with 'file://')
If I'm not mistaken, current implementation works only with local files. If http url will be passed, it must be downloaded firstly. Am I right? Or it already works with http urls also?

2016-12-16 14:21 UTC, dlatnikov approved these changes

2016-12-16 14:23 UTC, a-badaev approved these changes

2016-12-16 14:23 UTC, merged